const data = {
    products: [
      {
        name: 'TABLE 1',
        slug: 'Lorem ipsum dolor sit amet',
        category: 'centertable',
        image: require('./images/diningroom_table1.jpg'), // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Sed arcu tortor, tristique in sapien at, posuere tempor justo. Phasellus aliquet euismod aliquam. Morbi accumsan accumsan dui, ut eleifend nisl ultrices eget. Nullam congue libero ac eros molestie egestas. Phasellus ut sagittis leo. Etiam a posuere enim. Nam venenatis eros elementum turpis tincidunt sodales. Mauris id congue eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lorem ex, scelerisque ac pharetra',
      },
      {
        name: 'TABLE2 ',
        slug: 'Lorem ipsum dolor sit amet',
        category: 'chair',
        image: require('./images/diningroom_table2.jpg'),
        price: 250,
        countInStock: 20,
        brand: 'Lorem ipsum dolor sit amet',
        rating: 4.0,
        numReviews: 10,
        description: 'Sed arcu tortor, tristique in sapien at, posuere tempor justo. Phasellus aliquet euismod aliquam. Morbi accumsan accumsan dui, ut eleifend nisl ultrices eget. Nullam congue libero ac eros molestie egestas. Phasellus ut sagittis leo. Etiam a posuere enim. Nam venenatis eros elementum turpis tincidunt sodales. Mauris id congue eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lorem ex, scelerisque ac pharetract',
      },
      {
        name: 'TABLE 3',
        slug: 'Lorem ipsum dolor sit amet',
        category: 'chair',
        image: require('./images/diningroom_table3.jpg'),
        price: 25,
        countInStock: 15,
        brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 14,
        description: 'Sed arcu tortor, tristique in sapien at, posuere tempor justo. Phasellus aliquet euismod aliquam. Morbi accumsan accumsan dui, ut eleifend nisl ultrices eget. Nullam congue libero ac eros molestie egestas. Phasellus ut sagittis leo. Etiam a posuere enim. Nam venenatis eros elementum turpis tincidunt sodales. Mauris id congue eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lorem ex, scelerisque ac pharetract',
      },
      {
        name: 'TABLE 4',
        slug: 'aLorem ipsum dolor sit amet',
        category: 'chair',
        image: require('./images/diningroom_table4.jpg'),
        price: 65,
        countInStock: 5,
        brand: 'Lorem ipsum dolor sit amet',
        rating: 4.5,
        numReviews: 10,
        description: 'Sed arcu tortor, tristique in sapien at, posuere tempor justo. Phasellus aliquet euismod aliquam. Morbi accumsan accumsan dui, ut eleifend nisl ultrices eget. Nullam congue libero ac eros molestie egestas. Phasellus ut sagittis leo. Etiam a posuere enim. Nam venenatis eros elementum turpis tincidunt sodales. Mauris id congue eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lorem ex, scelerisque ac pharetract',
      },
    ],
  };
  export default data;